GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsIm5hbWUiOiJHdWlkbyBBcnlhc2F0eWEiLCJlbWFpbCI6Imd1aWRvYXJ5YUBnbWFpbC5jb20iLCJpYXQiOjE2MzgyNzkzMDYsImV4cCI6MTYzODI3OTMyNn0._dVtq1SJ62sYlMTzhZB5feRBrmfp3o2JahdO_nf9GDE
###
POST  http://localhost:5000/users
Content-Type: application/json

{
  "name": "Guido Aryasatya",
  "email": "guidoarya@gmail.com",
  "password": "123456",
  "confPassword": "123456",
  "nohp": "08132320912",
  "kota": "bekasi"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{
  "email": "guidoarya@gmail.com",
  "password": "123456"
}

###
GET  http://localhost:5000/token

###
DELETE  http://localhost:5000/logout

###
GET http://localhost:5000/umkm

###
GET http://localhost:5000/detail/12

###
POST http://localhost:5000/umkm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsIm5hbWUiOiJHdWlkbyBBcnlhc2F0eWEiLCJlbWFpbCI6Imd1aWRvYXJ5YUBnbWFpbC5jb20iLCJpYXQiOjE2MzgyNTc3NDMsImV4cCI6MTYzODI1Nzc2M30.vUnfvw4JURJZHB0EqJTugrhBbvSsa0fU_2Pr0JFCbSo

{
  "nama_umkm": "guido2 umkm",
  "lokasi": "Jl. rengasdengklok",
  "kota": "Jakarta",
  "deskripsi": "Umkm ini bergerak pada bidang kuliner, yang mana telah berdiri sejak tahun 1994. Aku cinta indonesia!",
  "kategori": "Kuliner",
  "nomor_hp": "082131237128",
  "jasa_produk": "makanan soto, sate, dan bakpao",
  "gambar": "pict.png"
}

